services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks:
      - main
    ports:
      - 8001:8001
    depends_on:
      - database
  database:
    image: "surrealdb/surrealdb"
    env_file:
      - surrealdb.env
    networks:
      - main
    ports:
      - 8000:8000
    volumes:
      - ./surrealdb-data:/surrealdb-data
    entrypoint:
      - /surreal
      - start
      - --auth
      - --query-timeout
      - 30m
      - --transaction-timeout
      - 1h
      - file:/surrealdb-data
networks:
  main:
    driver: bridge