services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    env_file: "./.env"
  database:
    image: "edgedb/edgedb"
    environment:
      EDGEDB_SERVER_SECURITY: "insecure_dev_mode"
    volumes:
      - "edgedb_data:/var/lib/edgedb/data"
volumes:
  queue_data:
  meili_data:
  edgedb_data:
