services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks:
      - main
    ports:
      - 8000:8000
  database:
    image: "edgedb/edgedb"
    networks:
      - main
    ports:
      - 5656:5656
    environment:
      EDGEDB_SERVER_SECURITY: "insecure_dev_mode"
    volumes:
      - "edgedb_data:/var/lib/edgedb/data"
      - "./internal/storage/database/edgedb/dbschema:/dbschema"
volumes:
  edgedb_data:
networks:
  main:
    driver: bridge